-- Run as ACCOUNTADMIN

CREATE WAREHOUSE ANALYTICS_WH
  WITH WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE ANALYTICS_DEV;
CREATE SCHEMA ANALYTICS_DEV.RAW;
CREATE SCHEMA ANALYTICS_DEV.STAGING;
CREATE SCHEMA ANALYTICS_DEV.INTERMEDIATE;
CREATE SCHEMA ANALYTICS_DEV.MARTS;

CREATE ROLE DBT_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON DATABASE ANALYTICS_DEV TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ANALYTICS_DEV TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ANALYTICS_DEV TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN ALL SCHEMAS IN DATABASE ANALYTICS_DEV TO ROLE DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN ALL SCHEMAS IN DATABASE ANALYTICS_DEV TO ROLE DBT_ROLE;

CREATE USER DBT_USER
    PASSWORD = 'YourStrongPassword!'
    DEFAULT_ROLE = DBT_ROLE
    DEFAULT_WAREHOUSE = ANALYTICS_WH
    DEFAULT_NAMESPACE = ANALYTICS_DEV.RAW;

GRANT ROLE DBT_ROLE TO USER DBT_USER;